name: ToucansAPi CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test
          - prod

env:
  AZURE_FUNCTIONAPP_NAME: func-toucans-${{ github.event.inputs.environment || 'dev' }}
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '9.0.x'
  RESOURCE_GROUP: rg-toucans-${{ github.event.inputs.environment || 'dev' }}
  LOCATION: eastus
  BICEP_FILE_PATH: 'infrastructure/bicep/main.bicep'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --logger trx

      - name: Publish code coverage
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: code-coverage-${{ github.sha }}
          path: '**/TestResults/**/coverage.cobertura.xml'
          retention-days: 14

      - name: Publish Function App
        run: |
          dotnet publish src/ToucansApi.Functions/ToucansApi.Functions.csproj \
            --configuration Release \
            --output ./publish \
            --no-restore \
            /p:DebugType=None \
            /p:DebugSymbols=false

      - name: Upload Function App artifact
        uses: actions/upload-artifact@v3
        with:
          name: function-app-${{ github.sha }}
          path: publish
          retention-days: 5

  deploy:
    needs: build
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.inputs.environment || 'dev' }}
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4

      - name: Download function artifact
        uses: actions/download-artifact@v3
        with:
          name: function-app-${{ github.sha }}
          path: ./function-app

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep template
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          template: ${{ env.BICEP_FILE_PATH }}
          parameters: >
            environment=${{ github.event.inputs.environment || 'dev' }}
            appName=toucans-api
            location=${{ env.LOCATION }}

      - name: Deploy Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: './function-app'
          respect-funcignore: true

      - name: Health check
        run: |
          sleep 30
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://${{ env.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net/api/health)
          if [ $STATUS_CODE -ne 200 ]; then
            echo "Health check failed with status code: $STATUS_CODE"
            exit 1
          fi
